spring:

  profiles:
    active: dev
  application:
    name: Onecrop
  datasource:
    url: jdbc:mysql://localhost:3306/onecrop?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: mysql
    show-sql: true